"use client"
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import {ThemeProvider} from 'next-themes'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-[#ece7f4] dark:bg-stone-900">
        <ThemeProvider enableSystem={true} attribute="class">
          <Navbar/>
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  )
}
